config/routes.rb
PullupLog::Application.routes.draw do
	resources :password_resets
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :relationships, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :exercises, only: [:create, :destroy]
  match '/signup', to: "users#new"
	match '/signin', to: "sessions#new"
	match '/signout', to: "sessions#destroy", via: :delete 
  get "static_pages/help"
	root to: 'static_pages#home'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
		user = User.find_by_email(params[:email])
		user.send_password_reset if user
		redirect_to root_url, :notice => "Email sent with password reset instructions."
	end
	
	def edit
		@user = User.find_by_password_reset_token!(params[:id])
	end
	
	def update
		@user = User.find_by_password_reset_token!(params[:id])
		if @user.password_reset_sent_at < 2.hours.ago
		  redirect_to new_password_reset_path, :alert => "Password reset has expired."
		elsif @user.update_attributes(params[:user])
		  redirect_to root_url, :notice => "Password has been reset."
		else
		  render :edit
		end
	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset Password") %>
<h1>Reset Password</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
			<%= render 'shared/error_messages' %>
				<%= f.label :password %>
				<%= f.password_field :password %>
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			<%= f.submit "Update Password", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_tag password_resets_path, :method => :post do %>
			<%= label_tag :email %>
			<%= text_field_tag :email, params[:email] %>
			<%= submit_tag "Reset Password", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>