config/routes.rb
PullupLog::Application.routes.draw do
	resources :password_resets
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :relationships, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :exercises, only: [:create, :destroy]
  match '/signup', to: "users#new"
	match '/signin', to: "sessions#new"
	match '/signout', to: "sessions#destroy", via: :delete 
  get "static_pages/help"
	root to: 'static_pages#home'

end

app/views/shared/_band_fields.html.erb
<div class = "checkbox">
	<%= f.check_box(:band_id, {},n, nil) %>
	<%= Band.all.first(n).last.name %>
</div>

<script></script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_exercise_form.html.erb
<%= form_for(@exercise) do |f| %>
	<% render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_field :reps, placeholder: "How many pullups did you do?" %>
	</div>
	<div class="field">
		What type of pullup did you do?
		<%= f.collection_select :pullup_type_id, PullupType.all, :id, :name %>
	</div>
		<% n=1 %>
		What bands did you use?
		<div class="checkboxes">
			<%= f.fields_for :bands_used do |builder| %>
				<%= render "shared/band_fields", {f: builder, n: n} %>
				<% n=n+1 %>
			<% end %>
		</div>
	<div class="field">
		<%= f.label :date, "When?",  style: "width:100px" %>
		<%= f.date_select :date, order: [:month, :day, :year], class: "dateselect" %>
	</div>

	<div class="field">
		<%= f.text_area :content, placeholder: "Comment on this exercise..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="exercises">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %> did <%= pluralize(feed_item.reps,feed_item.pullup_type.name.downcase) %> 
		<% if feed_item.bands.first.name == "None" %>
			unassisted
		<% else %>
			using 
			<% if feed_item.bands.count < 2 %>
				a 
			<% end %>
			<%= feed_item.bands.map(&:name).to_sentence.downcase %> 
			<% if feed_item.bands.count > 1 %>
				bands
			<% else %>
				band 
			<% end %>
		<% end %>
		on <%= feed_item.date %>
	</span>
	<span class="content"> 
	<span class="content"><%= wrap(feed_item.content) %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago
	</span>
	<% if current_user?(feed_item.user) %>
		<%= link_to "delete", feed_item, method: :delete, confirm: "You sure?", title: feed_item.content %>
	<% end %>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.exercises.count, "exercise") %>
</span>